version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y nodejs npm
            npm install
      - run:
          name: Run Tests
          command: |
            npm test

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip3 install awscli --upgrade
      - run:
          name: Deploy to AWS
          command: |
            ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-112-128-33.ap-northeast-1.compute.amazonaws.com "cd /path/to/app && git pull && npm install && pm2 restart all"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

