version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y nodejs npm
            npm install
      - run:
          name: Run Tests
          command: |
            npm test

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "your:ssh:key:2048 SHA256:MsPPWyBDcZgWZqYnPlJ6KdDKHUR6JKa2kkE3sv9ibI8 no comment (RSA)"  # CircleCIに追加したSSHキーのフィンガープリント
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
              cd /path/to/your/application
              git pull origin main
              npm install
              pm2 restart all
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

