version: 2.1

jobs:
  build_and_deploy:
    machine: true  # Dockerをフルにサポートするためにmachine executorを使用
    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - run:
          name: Deploy to EC2 via SSH
          command: |
            ssh -t -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST \<< 'EOF'
              if [ ! -f /home/ec2-user/.deployed ]; then
                echo "First deployment: Performing full setup."
                   # デプロイ先ディレクトリが存在しない場合は作成
                if [ ! -d  /home/ec2-user/app ]; then
                  echo "Creating deploy directory at Deploy"
                  sudo mkdir -p  /home/ec2-user/app
                fi
                cd /home/ec2-user/app
                git clone https://github.com/Y0r-K8m3-learning/advanced-project-flea.git .
                sudo docker-compose up -d --build
                sudo docker-compose exec php bash -c "composer install"
                sudo docker-compose exec php bash -c "cp -p .env.example .env"
                sudo docker-compose exec php bash -c "php artisan key:generate"
                sudo docker-compose exec php bash -c "php artisan migrate"
                sudo docker-compose exec php bash -c "php artisan db:seed"
                sudo docker-compose exec php bash -c "npm install"
                sudo docker-compose exec php bash -c "npm run build"
                sudo pm2 restart all
                sudo touch /home/ec2-user/app/.deployed
              else
                echo "Subsequent deployment: Pulling latest changes and updating."
                cd /home/ec2-user/app
                git pull origin main
                sudo docker-compose up -d --build
                sudo docker-compose exec php bash -c "composer install"
                sudo docker-compose exec php bash -c "php artisan migrate"
                sudo docker-compose exec php bash -c "php artisan db:seed"
                sudo docker-compose exec php bash -c "npm install"
                sudo docker-compose exec php bash -c "npm run build"
                sudo pm2 restart all
              fi
            EOF

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy
